#
###################################
# Site wide configuration
####################################
#
title:       "Allen's blog"
email:       "xudongzheng1225@gmail.com"
baseurl:     ""
description: 'A backend developer who loves design awesome things. Working for Huawei.'
url:         http://alleeen.github.io # the base hostname & protocol for your site

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Shanghai
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Allen
  avatar: avatar.jpg
  job: "Java & Scala Developer"
  bio: "A backend developer who loves design awesome things. Working for Huawei."
  email: xudongzheng1225@gmail.com
  disqus-shortname:
  twitter: xudongzheng1225 #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-36907890-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: alleeen #username
  stackoverflow: 1434570/allen-xudong-cheng #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: allenzheng1225
  flickr: #username
  codepen: #username
